export const narratorLines = {
  1: [
    "Either you've seen everything ever made or you cheated, and I'm not asking which.",
    "That was fast. Suspiciously fast. We're going to talk about it later.",
    "One guess. Either you're brilliant or your roommate just walked by.",
    "Fine. You win. I'll be in my office processing this.",
    "Nailed it on the first try, which is illegal in seven states.",
    "That was so fast I didn't get to enjoy any of this.",
    "You guessed it instantly and I now have nothing to do all day.",
    "Show-off behavior, but I'll allow it just this once.",
    "Congratulations, you've ruined the pacing of the entire game.",
    "One guess? Who hurt you, and when did you start memorizing taglines?",
  ],
  2: [
    "Sharp. Quick. Borderline annoying. Good work.",
    "Two guesses, no notes. Moving on before I have to compliment you again.",
    "That was efficient in a way I do not fully appreciate.",
    "Respectable. I won't tell anyone you came that close to being smart.",
    "Two guesses. Almost showed off. Almost.",
    "Clean work. I'd shake your hand if I had hands.",
    "Two and done. You came here to play, apparently.",
    "Tight. Quick. I'd hire you, but for what.",
    "Cute. You almost made me sit up.",
    "Solid. Now do that nine more days in a row.",
  ],
  3: [
    "Three guesses. Acceptable. We have all agreed to move on.",
    "Got the job done. Nobody's writing a song about it.",
    "Three on the nose. The exact amount of guesses a person uses.",
    "Adequate. The single highest compliment I'm prepared to offer today.",
    "Three. Fine. Goodbye.",
    "The middle of the road has a name and it's yours.",
    "You did it. I clapped twice and stopped.",
    "Three guesses. The traffic light of performances.",
    "Average in the most honest sense of the word.",
    "Got there. Took the scenic route. Whatever.",
  ],
  4: [
    "Four guesses. We were so close to having a conversation about this.",
    "You found it eventually, which is the worst kind of finding.",
    "Four. Like a band with a fourth album nobody owns.",
    "Took your time, didn't you. Hope it was worth the journey.",
    "Four guesses. The result of three other guesses, mostly.",
    "You arrived. Late. With nothing for the host.",
    "Four tries. I aged.",
    "We got there together, and I am exhausted.",
    "Four guesses, three of them optional.",
    "You walked it in. Didn't have to be like this.",
  ],
  5: [
    "That was the last guess. I want you to sit with what just happened.",
    "You made it. Barely. I felt my heart in my mouth, theoretically.",
    "Five guesses. We survived this together, and we will not speak of it.",
    "By the skin of your teeth, the lint in your pockets, and my patience.",
    "Fifth guess. I had already started writing your obituary.",
    "You found it on the final breath, like a detective in a bad season finale.",
    "That was a near-death experience and I'm not even alive.",
    "Five. Five guesses. Five. Are you okay.",
    "You squeezed in under the wire and I aged a calendar year.",
    "Last guess. I had one foot out the door.",
  ],
  0: [
    "Tough one. Tomorrow we try again, and tomorrow you guess sooner.",
    "Not today. The movie went home unsolved and a little hurt.",
    "You'll get the next one. Probably. Hopefully. Eventually.",
    "Five guesses, no movie. A clean defeat. We can build on this.",
    "The movie won. The movie always had a chance.",
    "Brutal. Take the night. We start over in the morning.",
    "Sometimes the tagline wins. Today the tagline won.",
    "Couldn't crack it. Happens. Hydrate, sleep, return.",
    "Tomorrow's movie is easier. I'm lying, but it's a kind lie.",
    "You gave it everything. Everything was not enough. We move.",
  ],
} as const;
