import type { ImportMovieEntry } from "./importMovie";

/**
 * Sports films not yet in the TAGLINES catalog (196 titles).
 * Cross-referenced against Supabase on 2026-06-04.
 *
 * Remakes share a catalogTitle so autocomplete shows the same name with (year).
 * Use year to disambiguate TMDB search; catalogTitle overrides stored title when needed.
 */
export const SPORTS_MOVIES_MISSING: ImportMovieEntry[] = [
  // Boxing / fighting
  { title: "Rocky III", year: 1982 },
  { title: "Rocky V", year: 1990 },
  { title: "Rocky Balboa", year: 2006 },
  { title: "Creed", year: 2015 },
  { title: "Creed II", year: 2018 },
  { title: "Creed III", year: 2023 },
  { title: "Cinderella Man", year: 2005 },
  { title: "Ali", year: 2001 },
  { title: "Southpaw", year: 2015 },
  { title: "Warrior", year: 2011 },
  { title: "The Hurricane", year: 1999 },
  { title: "Play It to the Bone", year: 1999 },
  { title: "The Champ", year: 1979 },
  { title: "Real Steel", year: 2011 },
  { title: "Nacho Libre", year: 2006 },
  { title: "Vision Quest", year: 1985 },
  { title: "No Holds Barred", year: 1989 },
  { title: "The Wrestler", year: 2008 },
  { title: "The Iron Claw", year: 2023 },
  { title: "Foxcatcher", year: 2014 },
  { title: "The Smashing Machine", year: 2025 },
  { title: "The Karate Kid Part III", year: 1989 },
  { title: "The Next Karate Kid", year: 1994 },
  { title: "The Karate Kid", year: 2010, catalogTitle: "The Karate Kid" },
  { title: "Bloodsport", year: 1988 },
  { title: "Best of the Best", year: 1989 },
  { title: "Never Back Down", year: 2008 },
  { title: "Kickboxer", year: 1989 },

  // Baseball
  { title: "Bull Durham", year: 1988 },
  { title: "The Natural", year: 1984 },
  { title: "Major League", year: 1989 },
  { title: "Major League II", year: 1994 },
  { title: "The Sandlot", year: 1993 },
  { title: "Rookie of the Year", year: 1993 },
  { title: "Angels in the Outfield", year: 1994 },
  { title: "The Rookie", year: 2002 },
  { title: "42", year: 2013 },
  { title: "Trouble with the Curve", year: 2012 },
  { title: "For Love of the Game", year: 1999 },
  { title: "Eight Men Out", year: 1988 },
  { title: "The Bad News Bears Go to Japan", year: 1978 },
  { title: "Bad News Bears", year: 2005, catalogTitle: "The Bad News Bears" },
  { title: "The Pride of the Yankees", year: 1942 },
  { title: "Fever Pitch", year: 2005 },
  { title: "Hardball", year: 2001 },
  { title: "The Fan", year: 1996 },
  { title: "Million Dollar Arm", year: 2014 },
  { title: "61*", year: 2001 },
  { title: "The Babe", year: 1992 },
  { title: "Mr. Baseball", year: 1992 },
  { title: "The Scout", year: 1994 },
  { title: "The Bingo Long Traveling All-Stars & Motor Kings", year: 1976 },
  { title: "Bang the Drum Slowly", year: 1973 },
  { title: "Cobb", year: 1994 },
  { title: "Little Big League", year: 1994 },
  { title: "Summer Catch", year: 2001 },
  { title: "The Perfect Game", year: 2009 },
  { title: "Mr. 3000", year: 2004 },
  { title: "The Slugger's Wife", year: 1985 },
  { title: "Talent for the Game", year: 1991 },
  { title: "The Benchwarmers", year: 2006 },

  // Football
  { title: "Brian's Song", year: 1971 },
  { title: "Johnny Be Good", year: 1988 },
  { title: "Remember the Titans", year: 2000 },
  { title: "Friday Night Lights", year: 2004 },
  { title: "Rudy", year: 1993 },
  { title: "Any Given Sunday", year: 1999 },
  { title: "The Replacements", year: 2000 },
  { title: "Varsity Blues", year: 1999 },
  { title: "Draft Day", year: 2014 },
  { title: "Invincible", year: 2006 },
  { title: "We Are Marshall", year: 2006 },
  { title: "The Program", year: 1993 },
  { title: "Concussion", year: 2015 },
  { title: "North Dallas Forty", year: 1979 },
  { title: "Little Giants", year: 1994 },
  { title: "Radio", year: 2003 },
  { title: "The Game Plan", year: 2007 },
  { title: "Necessary Roughness", year: 1991 },
  { title: "All the Right Moves", year: 1983 },
  { title: "Lucas", year: 1986 },
  { title: "Wildcats", year: 1986 },
  { title: "The Best of Times", year: 1986 },
  { title: "Everybody's All-American", year: 1988 },
  { title: "American Underdog", year: 2021 },
  { title: "80 for Brady", year: 2023 },
  { title: "The Express", year: 2008, tmdbId: 14325 },
  { title: "Gridiron Gang", year: 2006 },
  { title: "Leatherheads", year: 2008 },
  { title: "The Longest Yard", year: 1974, catalogTitle: "The Longest Yard" },

  // Basketball
  { title: "Hoosiers", year: 1986 },
  { title: "White Men Can't Jump", year: 1992 },
  { title: "He Got Game", year: 1998 },
  { title: "Blue Chips", year: 1994 },
  { title: "Above the Rim", year: 1994 },
  { title: "Coach Carter", year: 2005 },
  { title: "Love & Basketball", year: 2000 },
  { title: "Space Jam: A New Legacy", year: 2021 },
  { title: "Hustle", year: 2022 },
  { title: "Air", year: 2023 },
  { title: "Glory Road", year: 2006 },
  { title: "The Way Back", year: 2020 },
  { title: "Like Mike", year: 2002 },
  { title: "Semi-Pro", year: 2008 },
  { title: "Celtic Pride", year: 1996 },
  { title: "The Air Up There", year: 1994 },
  { title: "Sunset Park", year: 1996 },
  { title: "Eddie", year: 1996 },
  { title: "Rebound", year: 2005 },
  { title: "Uncle Drew", year: 2018 },

  // Hockey / skating
  { title: "Miracle", year: 2004 },
  { title: "Slap Shot", year: 1977 },
  { title: "The Mighty Ducks", year: 1992 },
  { title: "D2: The Mighty Ducks", year: 1994 },
  { title: "D3: The Mighty Ducks", year: 1996 },
  { title: "Mystery, Alaska", year: 1999 },
  { title: "Goon", year: 2011 },
  { title: "Youngblood", year: 1986 },
  { title: "Miracle on Ice", year: 1981 },
  { title: "The Cutting Edge", year: 1992 },
  { title: "The Cutting Edge: Going for the Gold", year: 2006 },
  { title: "The Cutting Edge: Chasing the Dream", year: 2008 },
  { title: "Ice Princess", year: 2005 },

  // Golf
  { title: "Happy Gilmore", year: 1996 },
  { title: "Happy Gilmore 2", year: 2025 },
  { title: "Tin Cup", year: 1996 },
  { title: "The Legend of Bagger Vance", year: 2000 },
  { title: "The Greatest Game Ever Played", year: 2005 },

  // Racing
  { title: "Rush", year: 2013 },
  { title: "Days of Thunder", year: 1990 },
  { title: "Talladega Nights: The Ballad of Ricky Bobby", year: 2006 },
  { title: "F1", year: 2025 },
  { title: "Gran Turismo", year: 2023 },
  { title: "Speed Racer", year: 2008 },
  { title: "Herbie Fully Loaded", year: 2005 },
  { title: "The Love Bug", year: 1968 },
  { title: "Le Mans", year: 1971 },
  { title: "Driven", year: 2001 },
  { title: "Need for Speed", year: 2014 },
  { title: "Turbo", year: 2013 },

  // Soccer
  { title: "Bend It Like Beckham", year: 2002 },
  { title: "Goal!", year: 2005 },
  { title: "Kicking & Screaming", year: 2005 },
  { title: "Shaolin Soccer", year: 2001 },
  { title: "Escape to Victory", year: 1981 },
  { title: "She's the Man", year: 2006 },
  { title: "The Big Green", year: 1995 },
  { title: "Ladybugs", year: 1992 },
  { title: "Mean Machine", year: 2001 },

  // Tennis
  { title: "Battle of the Sexes", year: 2017 },
  { title: "Wimbledon", year: 2004 },
  { title: "Borg vs McEnroe", year: 2017 },
  { title: "Challengers", year: 2024 },

  // Track / endurance
  { title: "Prefontaine", year: 1997 },
  { title: "Without Limits", year: 1998 },
  { title: "Race", year: 2016 },
  { title: "McFarland, USA", year: 2015 },
  { title: "Eddie the Eagle", year: 2016 },
  { title: "Personal Best", year: 1982 },
  { title: "The Boys in the Boat", year: 2023 },
  { title: "Oxford Blues", year: 1984 },
  { title: "Wind", year: 1992, tmdbId: 28881 },
  { title: "The World's Fastest Indian", year: 2005 },
  { title: "Cool Runnings", year: 1993 },

  // Surf / skate / extreme
  { title: "Soul Surfer", year: 2011 },
  { title: "Blue Crush", year: 2002 },
  { title: "North Shore", year: 1987 },
  { title: "Lords of Dogtown", year: 2005 },
  { title: "Airborne", year: 1993 },
  { title: "Whip It", year: 2009 },
  { title: "Gleaming the Cube", year: 1989 },
  { title: "BMX Bandits", year: 1983 },
  { title: "Rad", year: 1986 },
  { title: "Thrashin'", year: 1986 },
  { title: "Grind", year: 2003 },

  // Cheer / performance
  { title: "Bring It On", year: 2000 },
  { title: "Bring It On Again", year: 2004 },
  { title: "Bring It On: All or Nothing", year: 2006 },
  { title: "Bring It On: In It to Win It", year: 2007 },
  { title: "Stick It", year: 2006 },
  { title: "Gymkata", year: 1985 },
  { title: "American Anthem", year: 1986 },
  { title: "Blades of Glory", year: 2007 },

  // Other games
  { title: "The Big Lebowski", year: 1998 },
  { title: "Kingpin", year: 1996 },
  { title: "The Color of Money", year: 1986 },
  { title: "The Hustler", year: 1961 },
  { title: "Searching for Bobby Fischer", year: 1993 },
  { title: "Balls of Fury", year: 2007 },
  { title: "Dodgeball: A True Underdog Story", year: 2004 },
  { title: "Ping Pong Summer", year: 2014 },

  // Horse racing
  { title: "Secretariat", year: 2010 },
  { title: "Dreamer", year: 2005 },
  { title: "Hot to Trot", year: 1988 },
  { title: "Let It Ride", year: 1989 },
  { title: "The Black Stallion", year: 1979 },
  { title: "The Black Stallion Returns", year: 1983 },
  { title: "The Young Black Stallion", year: 2003 },
];
