/**
 * Full sports film master list from Sport movies.pdf (226 numbered titles).
 * Used to build the approved challenge pool vs Supabase.
 */

export interface SportsMasterEntry {
  /** 1-based index from the PDF master list */
  num: number;
  /** Display title from the PDF */
  listTitle: string;
  /** Match against movies.title (defaults to listTitle without year suffix) */
  catalogTitle?: string;
  /** When set, match this release year exactly */
  year?: number;
  category: string;
}

/** Strip PDF year suffixes like " — 2010" or "— 1974". */
export function parseListTitle(raw: string): { title: string; year?: number } {
  const m = raw.match(/^(.+?)\s*[—–-]\s*(\d{4})$/);
  if (m) return { title: m[1]!.trim(), year: parseInt(m[2]!, 10) };
  return { title: raw.trim() };
}

export const SPORTS_MOVIES_MASTER: SportsMasterEntry[] = [
  // Boxing / MMA / Fighting / Martial Arts / Wrestling
  { num: 1, listTitle: "Rocky", category: "Boxing / Fighting" },
  { num: 2, listTitle: "Rocky II", category: "Boxing / Fighting" },
  { num: 3, listTitle: "Rocky III", category: "Boxing / Fighting" },
  { num: 4, listTitle: "Rocky IV", category: "Boxing / Fighting" },
  { num: 5, listTitle: "Rocky V", category: "Boxing / Fighting" },
  { num: 6, listTitle: "Rocky Balboa", category: "Boxing / Fighting" },
  { num: 7, listTitle: "Creed", category: "Boxing / Fighting" },
  { num: 8, listTitle: "Creed II", category: "Boxing / Fighting" },
  { num: 9, listTitle: "Creed III", category: "Boxing / Fighting" },
  { num: 10, listTitle: "Raging Bull", category: "Boxing / Fighting" },
  { num: 11, listTitle: "The Fighter", category: "Boxing / Fighting" },
  { num: 12, listTitle: "Million Dollar Baby", category: "Boxing / Fighting" },
  { num: 13, listTitle: "Cinderella Man", category: "Boxing / Fighting" },
  { num: 14, listTitle: "Ali", category: "Boxing / Fighting" },
  { num: 15, listTitle: "Southpaw", category: "Boxing / Fighting" },
  { num: 16, listTitle: "Warrior", category: "Boxing / Fighting" },
  { num: 17, listTitle: "The Hurricane", category: "Boxing / Fighting" },
  { num: 18, listTitle: "Play It to the Bone", category: "Boxing / Fighting" },
  { num: 19, listTitle: "The Champ", category: "Boxing / Fighting" },
  { num: 20, listTitle: "Real Steel", category: "Boxing / Fighting" },
  { num: 21, listTitle: "Nacho Libre", category: "Boxing / Fighting" },
  { num: 22, listTitle: "Vision Quest", category: "Boxing / Fighting" },
  { num: 23, listTitle: "Over the Top", category: "Boxing / Fighting" },
  { num: 24, listTitle: "No Holds Barred", category: "Boxing / Fighting" },
  { num: 25, listTitle: "The Wrestler", category: "Boxing / Fighting" },
  { num: 26, listTitle: "The Iron Claw", category: "Boxing / Fighting" },
  { num: 27, listTitle: "Foxcatcher", category: "Boxing / Fighting" },
  { num: 28, listTitle: "The Smashing Machine", category: "Boxing / Fighting" },
  { num: 29, listTitle: "The Karate Kid", category: "Boxing / Fighting", year: 1984 },
  { num: 30, listTitle: "The Karate Kid Part II", category: "Boxing / Fighting" },
  { num: 31, listTitle: "The Karate Kid Part III", category: "Boxing / Fighting" },
  { num: 32, listTitle: "The Next Karate Kid", category: "Boxing / Fighting" },
  { num: 33, listTitle: "The Karate Kid — 2010", category: "Boxing / Fighting", catalogTitle: "The Karate Kid", year: 2010 },
  { num: 34, listTitle: "Bloodsport", category: "Boxing / Fighting" },
  { num: 35, listTitle: "Best of the Best", category: "Boxing / Fighting" },
  { num: 36, listTitle: "Never Back Down", category: "Boxing / Fighting" },
  { num: 37, listTitle: "Kickboxer", category: "Boxing / Fighting" },

  // Baseball
  { num: 38, listTitle: "Field of Dreams", category: "Baseball" },
  { num: 39, listTitle: "Bull Durham", category: "Baseball" },
  { num: 40, listTitle: "The Natural", category: "Baseball" },
  { num: 41, listTitle: "Major League", category: "Baseball" },
  { num: 42, listTitle: "Major League II", category: "Baseball" },
  { num: 43, listTitle: "A League of Their Own", category: "Baseball" },
  { num: 44, listTitle: "Moneyball", category: "Baseball" },
  { num: 45, listTitle: "The Sandlot", category: "Baseball" },
  { num: 46, listTitle: "Rookie of the Year", category: "Baseball" },
  { num: 47, listTitle: "Angels in the Outfield", category: "Baseball" },
  { num: 48, listTitle: "The Rookie", category: "Baseball" },
  { num: 49, listTitle: "42", category: "Baseball" },
  { num: 50, listTitle: "Trouble with the Curve", category: "Baseball" },
  { num: 51, listTitle: "For Love of the Game", category: "Baseball" },
  { num: 52, listTitle: "Eight Men Out", category: "Baseball" },
  { num: 53, listTitle: "The Bad News Bears", category: "Baseball", year: 1976 },
  { num: 54, listTitle: "The Bad News Bears in Breaking Training", category: "Baseball" },
  { num: 55, listTitle: "The Bad News Bears Go to Japan", category: "Baseball" },
  { num: 56, listTitle: "Bad News Bears — 2005", category: "Baseball", catalogTitle: "The Bad News Bears", year: 2005 },
  { num: 57, listTitle: "The Pride of the Yankees", category: "Baseball" },
  { num: 58, listTitle: "Fever Pitch", category: "Baseball" },
  { num: 59, listTitle: "Hardball", category: "Baseball" },
  { num: 60, listTitle: "The Fan", category: "Baseball" },
  { num: 61, listTitle: "Million Dollar Arm", category: "Baseball" },
  { num: 62, listTitle: "61*", category: "Baseball" },
  { num: 63, listTitle: "The Babe", category: "Baseball" },
  { num: 64, listTitle: "Mr. Baseball", category: "Baseball" },
  { num: 65, listTitle: "The Scout", category: "Baseball" },
  { num: 66, listTitle: "The Bingo Long Traveling All-Stars & Motor Kings", category: "Baseball" },
  { num: 67, listTitle: "Bang the Drum Slowly", category: "Baseball" },
  { num: 68, listTitle: "Cobb", category: "Baseball" },
  { num: 69, listTitle: "Little Big League", category: "Baseball" },
  { num: 70, listTitle: "Summer Catch", category: "Baseball" },
  { num: 71, listTitle: "The Perfect Game", category: "Baseball" },
  { num: 72, listTitle: "Mr. 3000", category: "Baseball" },
  { num: 73, listTitle: "The Slugger's Wife", category: "Baseball" },
  { num: 74, listTitle: "Talent for the Game", category: "Baseball" },
  { num: 75, listTitle: "The Benchwarmers", category: "Baseball" },

  // Football
  { num: 76, listTitle: "Brian's Song", category: "Football" },
  { num: 77, listTitle: "Johnny Be Good", category: "Football" },
  { num: 78, listTitle: "Remember the Titans", category: "Football" },
  { num: 79, listTitle: "Friday Night Lights", category: "Football" },
  { num: 80, listTitle: "Rudy", category: "Football" },
  { num: 81, listTitle: "The Blind Side", category: "Football" },
  { num: 82, listTitle: "Any Given Sunday", category: "Football" },
  { num: 83, listTitle: "The Longest Yard — 1974", category: "Football", catalogTitle: "The Longest Yard", year: 1974 },
  { num: 84, listTitle: "The Longest Yard — 2005", category: "Football", catalogTitle: "The Longest Yard", year: 2005 },
  { num: 85, listTitle: "The Replacements", category: "Football" },
  { num: 86, listTitle: "Varsity Blues", category: "Football" },
  { num: 87, listTitle: "Draft Day", category: "Football" },
  { num: 88, listTitle: "Invincible", category: "Football" },
  { num: 89, listTitle: "We Are Marshall", category: "Football" },
  { num: 90, listTitle: "The Program", category: "Football" },
  { num: 91, listTitle: "Concussion", category: "Football" },
  { num: 92, listTitle: "North Dallas Forty", category: "Football" },
  { num: 93, listTitle: "Little Giants", category: "Football" },
  { num: 94, listTitle: "Radio", category: "Football" },
  { num: 95, listTitle: "The Game Plan", category: "Football" },
  { num: 96, listTitle: "Necessary Roughness", category: "Football" },
  { num: 97, listTitle: "All the Right Moves", category: "Football" },
  { num: 98, listTitle: "Lucas", category: "Football" },
  { num: 99, listTitle: "Wildcats", category: "Football" },
  { num: 100, listTitle: "The Best of Times", category: "Football" },
  { num: 101, listTitle: "Everybody's All-American", category: "Football" },
  { num: 102, listTitle: "American Underdog", category: "Football" },
  { num: 103, listTitle: "80 for Brady", category: "Football" },
  { num: 104, listTitle: "The Express", category: "Football" },
  { num: 105, listTitle: "Gridiron Gang", category: "Football" },
  { num: 106, listTitle: "Leatherheads", category: "Football" },
  { num: 107, listTitle: "The Waterboy", category: "Football" },

  // Basketball
  { num: 108, listTitle: "Hoosiers", category: "Basketball" },
  { num: 109, listTitle: "White Men Can't Jump", category: "Basketball" },
  { num: 110, listTitle: "He Got Game", category: "Basketball" },
  { num: 111, listTitle: "Blue Chips", category: "Basketball" },
  { num: 112, listTitle: "Above the Rim", category: "Basketball" },
  { num: 113, listTitle: "Coach Carter", category: "Basketball" },
  { num: 114, listTitle: "Love & Basketball", category: "Basketball" },
  { num: 115, listTitle: "Space Jam", category: "Basketball" },
  { num: 116, listTitle: "Space Jam: A New Legacy", category: "Basketball" },
  { num: 117, listTitle: "Hustle", category: "Basketball" },
  { num: 118, listTitle: "Air", category: "Basketball" },
  { num: 119, listTitle: "Glory Road", category: "Basketball" },
  { num: 120, listTitle: "The Way Back", category: "Basketball" },
  { num: 121, listTitle: "Like Mike", category: "Basketball" },
  { num: 122, listTitle: "Semi-Pro", category: "Basketball" },
  { num: 123, listTitle: "Celtic Pride", category: "Basketball" },
  { num: 124, listTitle: "The Air Up There", category: "Basketball" },
  { num: 125, listTitle: "Sunset Park", category: "Basketball" },
  { num: 126, listTitle: "Eddie", category: "Basketball" },
  { num: 127, listTitle: "Rebound", category: "Basketball" },
  { num: 128, listTitle: "Uncle Drew", category: "Basketball" },

  // Hockey / Ice Skating
  { num: 129, listTitle: "Miracle", category: "Hockey / Skating" },
  { num: 130, listTitle: "Slap Shot", category: "Hockey / Skating" },
  { num: 131, listTitle: "The Mighty Ducks", category: "Hockey / Skating" },
  { num: 132, listTitle: "D2: The Mighty Ducks", category: "Hockey / Skating" },
  { num: 133, listTitle: "D3: The Mighty Ducks", category: "Hockey / Skating" },
  { num: 134, listTitle: "Mystery, Alaska", category: "Hockey / Skating" },
  { num: 135, listTitle: "Goon", category: "Hockey / Skating" },
  { num: 136, listTitle: "Youngblood", category: "Hockey / Skating" },
  { num: 137, listTitle: "Miracle on Ice", category: "Hockey / Skating" },
  { num: 138, listTitle: "The Cutting Edge", category: "Hockey / Skating" },
  { num: 139, listTitle: "The Cutting Edge 2: Going for the Gold", category: "Hockey / Skating", catalogTitle: "The Cutting Edge: Going for the Gold" },
  { num: 140, listTitle: "The Cutting Edge 3: Chasing the Dream", category: "Hockey / Skating", catalogTitle: "The Cutting Edge: Chasing the Dream" },
  { num: 141, listTitle: "Ice Princess", category: "Hockey / Skating" },

  // Golf
  { num: 142, listTitle: "Happy Gilmore", category: "Golf" },
  { num: 143, listTitle: "Happy Gilmore 2", category: "Golf" },
  { num: 144, listTitle: "Tin Cup", category: "Golf" },
  { num: 145, listTitle: "Caddyshack", category: "Golf" },
  { num: 146, listTitle: "The Legend of Bagger Vance", category: "Golf" },
  { num: 147, listTitle: "The Greatest Game Ever Played", category: "Golf" },

  // Racing
  { num: 148, listTitle: "Ford v Ferrari", category: "Racing" },
  { num: 149, listTitle: "Rush", category: "Racing" },
  { num: 150, listTitle: "Days of Thunder", category: "Racing" },
  { num: 151, listTitle: "Talladega Nights: The Ballad of Ricky Bobby", category: "Racing" },
  { num: 152, listTitle: "F1 / F1: The Movie", category: "Racing", catalogTitle: "F1", year: 2025 },
  { num: 153, listTitle: "Gran Turismo", category: "Racing" },
  { num: 154, listTitle: "Speed Racer", category: "Racing" },
  { num: 155, listTitle: "Herbie Fully Loaded", category: "Racing" },
  { num: 156, listTitle: "The Love Bug", category: "Racing" },
  { num: 157, listTitle: "Le Mans", category: "Racing" },
  { num: 158, listTitle: "Driven", category: "Racing" },
  { num: 159, listTitle: "Need for Speed", category: "Racing" },
  { num: 160, listTitle: "The Fast and the Furious", category: "Racing" },
  { num: 161, listTitle: "Cars", category: "Racing" },
  { num: 162, listTitle: "Cars 2", category: "Racing" },
  { num: 163, listTitle: "Cars 3", category: "Racing" },
  { num: 164, listTitle: "Turbo", category: "Racing" },

  // Soccer
  { num: 165, listTitle: "Bend It Like Beckham", category: "Soccer" },
  { num: 166, listTitle: "Goal!", category: "Soccer" },
  { num: 167, listTitle: "Kicking & Screaming", category: "Soccer" },
  { num: 168, listTitle: "Shaolin Soccer", category: "Soccer" },
  { num: 169, listTitle: "Victory / Escape to Victory", category: "Soccer", catalogTitle: "Victory", year: 1981 },
  { num: 170, listTitle: "She's the Man", category: "Soccer" },
  { num: 171, listTitle: "The Big Green", category: "Soccer" },
  { num: 172, listTitle: "Ladybugs", category: "Soccer" },
  { num: 173, listTitle: "Mean Machine", category: "Soccer" },

  // Tennis
  { num: 174, listTitle: "Battle of the Sexes", category: "Tennis" },
  { num: 175, listTitle: "Wimbledon", category: "Tennis" },
  { num: 176, listTitle: "Borg vs. McEnroe", category: "Tennis", catalogTitle: "Borg vs McEnroe" },
  { num: 177, listTitle: "King Richard", category: "Tennis" },
  { num: 178, listTitle: "Challengers", category: "Tennis" },

  // Track / Olympics / Endurance
  { num: 179, listTitle: "Chariots of Fire", category: "Track / Olympics" },
  { num: 180, listTitle: "Prefontaine", category: "Track / Olympics" },
  { num: 181, listTitle: "Without Limits", category: "Track / Olympics" },
  { num: 182, listTitle: "Race", category: "Track / Olympics" },
  { num: 183, listTitle: "McFarland, USA", category: "Track / Olympics" },
  { num: 184, listTitle: "Eddie the Eagle", category: "Track / Olympics" },
  { num: 185, listTitle: "Personal Best", category: "Track / Olympics" },
  { num: 186, listTitle: "The Boys in the Boat", category: "Track / Olympics" },
  { num: 187, listTitle: "Oxford Blues", category: "Track / Olympics" },
  { num: 188, listTitle: "Wind", category: "Track / Olympics" },
  { num: 189, listTitle: "The World's Fastest Indian", category: "Track / Olympics" },
  { num: 190, listTitle: "Cool Runnings", category: "Track / Olympics" },

  // Surf / Skate / Extreme
  { num: 191, listTitle: "Soul Surfer", category: "Surf / Skate / Extreme" },
  { num: 192, listTitle: "Blue Crush", category: "Surf / Skate / Extreme" },
  { num: 193, listTitle: "North Shore", category: "Surf / Skate / Extreme" },
  { num: 194, listTitle: "Lords of Dogtown", category: "Surf / Skate / Extreme" },
  { num: 195, listTitle: "Airborne", category: "Surf / Skate / Extreme" },
  { num: 196, listTitle: "Whip It", category: "Surf / Skate / Extreme" },
  { num: 197, listTitle: "Gleaming the Cube", category: "Surf / Skate / Extreme" },
  { num: 198, listTitle: "BMX Bandits", category: "Surf / Skate / Extreme" },
  { num: 199, listTitle: "Rad", category: "Surf / Skate / Extreme" },
  { num: 200, listTitle: "Thrashin'", category: "Surf / Skate / Extreme" },
  { num: 201, listTitle: "Grind", category: "Surf / Skate / Extreme" },

  // Cheer / Gymnastics
  { num: 202, listTitle: "Bring It On", category: "Cheer / Gymnastics" },
  { num: 203, listTitle: "Bring It On Again", category: "Cheer / Gymnastics" },
  { num: 204, listTitle: "Bring It On: All or Nothing", category: "Cheer / Gymnastics" },
  { num: 205, listTitle: "Bring It On: In It to Win It", category: "Cheer / Gymnastics" },
  { num: 206, listTitle: "Stick It", category: "Cheer / Gymnastics" },
  { num: 207, listTitle: "Gymkata", category: "Cheer / Gymnastics" },
  { num: 208, listTitle: "American Anthem", category: "Cheer / Gymnastics" },
  { num: 209, listTitle: "Blades of Glory", category: "Cheer / Gymnastics" },

  // Bowling / Pool / Chess / Other
  { num: 210, listTitle: "The Big Lebowski", category: "Other Games" },
  { num: 211, listTitle: "Kingpin", category: "Other Games" },
  { num: 212, listTitle: "The Color of Money", category: "Other Games" },
  { num: 213, listTitle: "The Hustler", category: "Other Games" },
  { num: 214, listTitle: "Searching for Bobby Fischer", category: "Other Games" },
  { num: 215, listTitle: "Balls of Fury", category: "Other Games" },
  { num: 216, listTitle: "Dodgeball: A True Underdog Story", category: "Other Games" },
  { num: 217, listTitle: "Marty Supreme", category: "Other Games" },
  { num: 218, listTitle: "Ping Pong Summer", category: "Other Games" },

  // Horse Racing / Equestrian
  { num: 219, listTitle: "Seabiscuit", category: "Horse Racing" },
  { num: 220, listTitle: "Secretariat", category: "Horse Racing" },
  { num: 221, listTitle: "Dreamer", category: "Horse Racing" },
  { num: 222, listTitle: "Hot to Trot", category: "Horse Racing" },
  { num: 223, listTitle: "Let It Ride", category: "Horse Racing" },
  { num: 224, listTitle: "The Black Stallion", category: "Horse Racing" },
  { num: 225, listTitle: "The Black Stallion Returns", category: "Horse Racing" },
  { num: 226, listTitle: "The Young Black Stallion", category: "Horse Racing" },
];
