/** Master movie list — merged from all decade tabs (1970s–2020s) plus the
 *  Oscars tab. Deduplicated (case-insensitive); every Oscar title is included.
 *  Sequels are kept as distinct films. Edit as needed. */

export const STARTER_MOVIES: string[] = [
  "Star Wars: Episode IV - A New Hope",
  "Superman",
  "The Godfather",
  "Jaws",
  "Grease",
  "Smokey and the Bandit",
  "National Lampoon's Animal House",
  "Close Encounters of the Third Kind",
  "Kramer vs. Kramer",
  "Enter the Dragon",
  "Saturday Night Fever",
  "The Exorcist",
  "The Amityville Horror",
  "Every Which Way but Loose",
  "Rocky II",
  "The Way of the Dragon",
  "Apocalypse Now",
  "The Goodbye Girl",
  "Star Trek: The Motion Picture",
  "Heaven Can Wait",
  "Alien",
  "The Sting",
  "Hooper",
  "Jaws 2",
  "Up in Smoke",
  "10",
  "The Jerk",
  "Moonraker",
  "The Muppet Movie",
  "One Flew Over the Cuckoo's Nest",
  "Rocky",
  "American Graffiti",
  "A Bridge Too Far",
  "Love Story",
  "The Towering Inferno",
  "Revenge of the Pink Panther",
  "The Deer Hunter",
  "The Godfather Part II",
  "The Deep",
  "The Spy Who Loved Me",
  "Blazing Saddles",
  "Airport",
  "The Poseidon Adventure",
  "Oh, God!",
  "Fiddler on the Roof",
  "Young Frankenstein",
  "Annie Hall",
  "A Star Is Born",
  "King Kong",
  "Earthquake",
  "Patton",
  "MASH",
  "The French Connection",
  "Dirty Harry",
  "Diamonds Are Forever",
  "Summer of '42",
  "Carnal Knowledge",
  "What's Up, Doc?",
  "The Last Picture Show",
  "The Cowboys",
  "Deliverance",
  "The Getaway",
  "Live and Let Die",
  "Paper Moon",
  "Serpico",
  "Magnum Force",
  "The Longest Yard",
  "Chinatown",
  "The Trial of Billy Jack",
  "Murder on the Orient Express",
  "The Man with the Golden Gun",
  "The Texas Chain Saw Massacre",
  "Tommy",
  "Shampoo",
  "Dog Day Afternoon",
  "Three Days of the Condor",
  "Funny Lady",
  "The Return of the Pink Panther",
  "The Omen",
  "All the President's Men",
  "Silver Streak",
  "The Bad News Bears",
  "Carrie",
  "Network",
  "Taxi Driver",
  "The Outlaw Josey Wales",
  "Marathon Man",
  "Logan's Run",
  "Fun with Dick and Jane",
  "The Rescuers",
  "The Enforcer",
  "The Bad News Bears in Breaking Training",
  "Herbie Goes to Monte Carlo",
  "Looking for Mr. Goodbar",
  "The Wiz",
  "Halloween",
  "Midnight Express",
  "The China Syndrome",
  "Breaking Away",
  "Escape from Alcatraz",
  "E.T. the Extra-Terrestrial",
  "Star Wars: Episode V - The Empire Strikes Back",
  "Star Wars: Episode VI - Return of the Jedi",
  "Indiana Jones and the Last Crusade",
  "Batman",
  "Raiders of the Lost Ark",
  "Ghostbusters",
  "Beverly Hills Cop",
  "Back to the Future",
  "Top Gun",
  "Rain Man",
  "Three Men and a Baby",
  "Who Framed Roger Rabbit",
  "Crocodile Dundee",
  "Fatal Attraction",
  "Beverly Hills Cop II",
  "Rambo: First Blood Part II",
  "Rocky IV",
  "The Karate Kid Part II",
  "Coming to America",
  "Good Morning, Vietnam",
  "Cocoon",
  "The Color Purple",
  "Tootsie",
  "An Officer and a Gentleman",
  "The Little Mermaid",
  "The Untouchables",
  "The Golden Child",
  "Twins",
  "Big",
  "Die Hard",
  "Lethal Weapon 2",
  "Lethal Weapon",
  "The War of the Roses",
  "Working Girl",
  "A Fish Called Wanda",
  "Dead Poets Society",
  "Field of Dreams",
  "Driving Miss Daisy",
  "Born on the Fourth of July",
  "Platoon",
  "The Terminator",
  "Terminator 2: Judgment Day",
  "Predator",
  "Aliens",
  "The Shining",
  "A Nightmare on Elm Street",
  "Friday the 13th",
  "Halloween II",
  "The Thing",
  "Poltergeist",
  "Gremlins",
  "The Fly",
  "Child's Play",
  "Beetlejuice",
  "The Lost Boys",
  "The Goonies",
  "Stand by Me",
  "The Breakfast Club",
  "Ferris Bueller's Day Off",
  "Sixteen Candles",
  "Pretty in Pink",
  "Say Anything...",
  "When Harry Met Sally...",
  "Moonstruck",
  "Broadcast News",
  "Terms of Endearment",
  "The Big Chill",
  "Risky Business",
  "Footloose",
  "Dirty Dancing",
  "Flashdance",
  "Fame",
  "9 to 5",
  "Airplane!",
  "The Blues Brothers",
  "Trading Places",
  "Caddyshack",
  "National Lampoon's Vacation",
  "National Lampoon's Christmas Vacation",
  "Planes, Trains and Automobiles",
  "Uncle Buck",
  "Spaceballs",
  "The Naked Gun: From the Files of Police Squad!",
  "This Is Spinal Tap",
  "Raising Arizona",
  "RoboCop",
  "The Princess Bride",
  "The NeverEnding Story",
  "Labyrinth",
  "The Dark Crystal",
  "Willow",
  "Highlander",
  "Conan the Barbarian",
  "Scarface",
  "The Outsiders",
  "Raging Bull",
  "Amadeus",
  "Blue Velvet",
  "Do the Right Thing",
  "Titanic",
  "Star Wars: Episode I - The Phantom Menace",
  "Jurassic Park",
  "Independence Day",
  "The Lion King",
  "Forrest Gump",
  "The Sixth Sense",
  "The Lost World: Jurassic Park",
  "Men in Black",
  "Armageddon",
  "Ghost",
  "Aladdin",
  "Twister",
  "Toy Story 2",
  "Saving Private Ryan",
  "Home Alone",
  "The Matrix",
  "Pretty Woman",
  "Mission: Impossible",
  "Tarzan",
  "Mrs. Doubtfire",
  "Dances with Wolves",
  "The Mummy",
  "The Bodyguard",
  "Beauty and the Beast",
  "Toy Story",
  "The Fugitive",
  "True Lies",
  "Apollo 13",
  "Liar Liar",
  "Die Hard with a Vengeance",
  "Austin Powers: The Spy Who Shagged Me",
  "Notting Hill",
  "Shakespeare in Love",
  "A Bug's Life",
  "There's Something About Mary",
  "Good Will Hunting",
  "Air Force One",
  "The Rock",
  "Face/Off",
  "Jerry Maguire",
  "The Firm",
  "Basic Instinct",
  "GoldenEye",
  "Tomorrow Never Dies",
  "The World Is Not Enough",
  "The Mask",
  "Speed",
  "Hook",
  "The Flintstones",
  "Batman Forever",
  "Batman Returns",
  "Batman & Robin",
  "The Santa Clause",
  "Jumanji",
  "101 Dalmatians",
  "Casper",
  "Stuart Little",
  "Space Jam",
  "The Waterboy",
  "The Wedding Singer",
  "Ace Ventura: Pet Detective",
  "Ace Ventura: When Nature Calls",
  "Dumb and Dumber",
  "Wayne's World",
  "Wayne's World 2",
  "My Best Friend's Wedding",
  "Sleepless in Seattle",
  "You've Got Mail",
  "Four Weddings and a Funeral",
  "Clueless",
  "10 Things I Hate About You",
  "American Pie",
  "Scream",
  "Scream 2",
  "I Know What You Did Last Summer",
  "The Blair Witch Project",
  "Interview with the Vampire",
  "Bram Stoker's Dracula",
  "The Silence of the Lambs",
  "Se7en",
  "Cape Fear",
  "Misery",
  "The Addams Family",
  "Addams Family Values",
  "The Nightmare Before Christmas",
  "Hocus Pocus",
  "Edward Scissorhands",
  "Groundhog Day",
  "A League of Their Own",
  "The Truman Show",
  "As Good as It Gets",
  "Philadelphia",
  "A Few Good Men",
  "The Green Mile",
  "Schindler's List",
  "Unforgiven",
  "Braveheart",
  "Goodfellas",
  "Pulp Fiction",
  "Fargo",
  "Avatar",
  "The Lord of the Rings: The Return of the King",
  "Pirates of the Caribbean: Dead Man's Chest",
  "The Dark Knight",
  "Harry Potter and the Philosopher's Stone",
  "Harry Potter and the Sorcerer's Stone",
  "Pirates of the Caribbean: At World's End",
  "Harry Potter and the Order of the Phoenix",
  "Harry Potter and the Half-Blood Prince",
  "The Lord of the Rings: The Two Towers",
  "Shrek 2",
  "Harry Potter and the Goblet of Fire",
  "Spider-Man 3",
  "Ice Age: Dawn of the Dinosaurs",
  "Harry Potter and the Chamber of Secrets",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Finding Nemo",
  "Star Wars: Episode III - Revenge of the Sith",
  "Transformers: Revenge of the Fallen",
  "Spider-Man",
  "Shrek the Third",
  "Spider-Man 2",
  "The Passion of the Christ",
  "Mamma Mia!",
  "Madagascar: Escape 2 Africa",
  "Casino Royale",
  "War of the Worlds",
  "Quantum of Solace",
  "I Am Legend",
  "Iron Man",
  "Night at the Museum",
  "Mission: Impossible 2",
  "The Day After Tomorrow",
  "Madagascar",
  "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
  "The Incredibles",
  "Hancock",
  "Ratatouille",
  "Monsters, Inc.",
  "WALL-E",
  "The Matrix Reloaded",
  "Up",
  "The Hangover",
  "Meet the Fockers",
  "How the Grinch Stole Christmas",
  "Cars",
  "Bruce Almighty",
  "X2",
  "The Last Samurai",
  "300",
  "Ocean's Eleven",
  "Ocean's Twelve",
  "Ocean's Thirteen",
  "The Bourne Identity",
  "The Bourne Supremacy",
  "The Bourne Ultimatum",
  "Gladiator",
  "Cast Away",
  "What Women Want",
  "Pearl Harbor",
  "The Mummy Returns",
  "The Fast and the Furious",
  "2 Fast 2 Furious",
  "Fast & Furious",
  "X-Men",
  "X-Men: The Last Stand",
  "Batman Begins",
  "Superman Returns",
  "National Treasure",
  "National Treasure: Book of Secrets",
  "The Da Vinci Code",
  "Angels & Demons",
  "Troy",
  "The Departed",
  "Catch Me If You Can",
  "Minority Report",
  "A Beautiful Mind",
  "Chicago",
  "Moulin Rouge!",
  "Slumdog Millionaire",
  "No Country for Old Men",
  "There Will Be Blood",
  "The Curious Case of Benjamin Button",
  "The Aviator",
  "Million Dollar Baby",
  "Brokeback Mountain",
  "Juno",
  "Little Miss Sunshine",
  "Lost in Translation",
  "Eternal Sunshine of the Spotless Mind",
  "Almost Famous",
  "Mean Girls",
  "Legally Blonde",
  "The Devil Wears Prada",
  "Wedding Crashers",
  "The 40-Year-Old Virgin",
  "Superbad",
  "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
  "Anchorman: The Legend of Ron Burgundy",
  "Avengers: Endgame",
  "Star Wars: Episode VII - The Force Awakens",
  "Avengers: Infinity War",
  "Jurassic World",
  "The Avengers",
  "Furious 7",
  "Frozen II",
  "Avengers: Age of Ultron",
  "Black Panther",
  "Harry Potter and the Deathly Hallows: Part 2",
  "Star Wars: Episode VIII - The Last Jedi",
  "Jurassic World: Fallen Kingdom",
  "Frozen",
  "Incredibles 2",
  "The Fate of the Furious",
  "Iron Man 3",
  "Minions",
  "Captain America: Civil War",
  "Aquaman",
  "Spider-Man: Far From Home",
  "Captain Marvel",
  "Transformers: Dark of the Moon",
  "Skyfall",
  "Transformers: Age of Extinction",
  "The Dark Knight Rises",
  "Joker",
  "Toy Story 4",
  "Toy Story 3",
  "Pirates of the Caribbean: On Stranger Tides",
  "Rogue One: A Star Wars Story",
  "Finding Dory",
  "Zootopia",
  "The Hobbit: An Unexpected Journey",
  "The Hobbit: The Desolation of Smaug",
  "The Hobbit: The Battle of the Five Armies",
  "Alice in Wonderland",
  "Despicable Me 3",
  "The Jungle Book",
  "Jumanji: Welcome to the Jungle",
  "The Hunger Games: Catching Fire",
  "Guardians of the Galaxy Vol. 2",
  "Inside Out",
  "Venom",
  "Thor: Ragnarok",
  "Inception",
  "Wonder Woman",
  "Hi, Mom",
  "Fantastic Beasts and Where to Find Them",
  "Shrek Forever After",
  "The Secret Life of Pets",
  "Despicable Me 2",
  "The Amazing Spider-Man",
  "Mission: Impossible - Fallout",
  "The Hunger Games: Mockingjay - Part 1",
  "Gravity",
  "Captain America: The Winter Soldier",
  "Dawn of the Planet of the Apes",
  "The Twilight Saga: Breaking Dawn - Part 2",
  "The Twilight Saga: Breaking Dawn - Part 1",
  "The Hunger Games",
  "Mission: Impossible - Ghost Protocol",
  "Doctor Strange",
  "Interstellar",
  "Coco",
  "Bohemian Rhapsody",
  "Madagascar 3: Europe's Most Wanted",
  "Suicide Squad",
  "X-Men: Days of Future Past",
  "The Amazing Spider-Man 2",
  "Maleficent",
  "It",
  "Moana",
  "Deadpool 2",
  "Deadpool",
  "Big Hero 6",
  "The Martian",
  "Logan",
  "The Revenant",
  "Life of Pi",
  "Fast Five",
  "Tangled",
  "How to Train Your Dragon",
  "How to Train Your Dragon 2",
  "How to Train Your Dragon: The Hidden World",
  "Wreck-It Ralph",
  "Ralph Breaks the Internet",
  "Brave",
  "Monsters University",
  "Cars 2",
  "Cars 3",
  "Kung Fu Panda 2",
  "Kung Fu Panda 3",
  "Hotel Transylvania",
  "Hotel Transylvania 2",
  "Hotel Transylvania 3: Summer Vacation",
  "The Croods",
  "Rio",
  "Rio 2",
  "Sing",
  "Avatar: The Way of Water",
  "Spider-Man: No Way Home",
  "Inside Out 2",
  "Top Gun: Maverick",
  "Barbie",
  "The Super Mario Bros. Movie",
  "Deadpool & Wolverine",
  "Moana 2",
  "Jurassic World Dominion",
  "Despicable Me 4",
  "Oppenheimer",
  "The Batman",
  "Dune",
  "Dune: Part Two",
  "Doctor Strange in the Multiverse of Madness",
  "Black Panther: Wakanda Forever",
  "Thor: Love and Thunder",
  "Guardians of the Galaxy Vol. 3",
  "Ant-Man and the Wasp: Quantumania",
  "Black Widow",
  "Shang-Chi and the Legend of the Ten Rings",
  "Eternals",
  "The Marvels",
  "Venom: Let There Be Carnage",
  "Venom: The Last Dance",
  "Godzilla vs. Kong",
  "Godzilla x Kong: The New Empire",
  "Kingdom of the Planet of the Apes",
  "No Time to Die",
  "Mission: Impossible - Dead Reckoning Part One",
  "Mission: Impossible: The Final Reckoning",
  "Fast X",
  "F9: The Fast Saga",
  "Bad Boys for Life",
  "Bad Boys: Ride or Die",
  "A Quiet Place Part II",
  "A Quiet Place: Day One",
  "Scream VI",
  "Halloween Kills",
  "Halloween Ends",
  "The Conjuring: The Devil Made Me Do It",
  "The Nun II",
  "M3GAN",
  "Smile",
  "Smile 2",
  "Five Nights at Freddy's",
  "The Black Phone",
  "Nope",
  "Us",
  "Get Out",
  "It Ends with Us",
  "Anyone But You",
  "The Lost City",
  "Ticket to Paradise",
  "Where the Crawdads Sing",
  "Elvis",
  "Wonka",
  "Wicked",
  "Mufasa: The Lion King",
  "Lightyear",
  "Elemental",
  "Turning Red",
  "Soul",
  "Luca",
  "Raya and the Last Dragon",
  "Encanto",
  "Wish",
  "Puss in Boots: The Last Wish",
  "Minions: The Rise of Gru",
  "Kung Fu Panda 4",
  "Sonic the Hedgehog",
  "Sonic the Hedgehog 2",
  "Sonic the Hedgehog 3",
  "The Bad Guys",
  "Migration",
  "The Wild Robot",
  "Spider-Man: Across the Spider-Verse",
  "Teenage Mutant Ninja Turtles: Mutant Mayhem",
  "Transformers: Rise of the Beasts",
  "Transformers One",
  "The Flash",
  "Aquaman and the Lost Kingdom",
  "Shazam! Fury of the Gods",
  "Blue Beetle",
  "The Suicide Squad",
  "Wonder Woman 1984",
  "Tenet",
  "The Creator",
  "Everything Everywhere All at Once",
  "The Banshees of Inisherin",
  "The Fabelmans",
  "Killers of the Flower Moon",
  "Poor Things",
  "The Holdovers",
  "Anora",
  "The Brutalist",
  "Past Lives",
  "Tár",
  "Triangle of Sadness",
  "All Quiet on the Western Front",
  "Parasite",
  "Another Round",
  "Drive My Car",
  "The Zone of Interest",
  "Anatomy of a Fall",
  "The Boy and the Heron",
  "Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train",
  "The Eight Hundred",
  "My People, My Homeland",
  "Ne Zha 2",
  "Zootopia 2",
  "Lilo & Stitch",
  "A Minecraft Movie",
  "Jurassic World Rebirth",
  "F1",
  "The Conversation",
  "Lenny",
  "Barry Lyndon",
  "Nashville",
  "Bound for Glory",
  "Julia",
  "The Turning Point",
  "Coming Home",
  "An Unmarried Woman",
  "All That Jazz",
  "Norma Rae",
  "Coal Miner's Daughter",
  "The Elephant Man",
  "Ordinary People",
  "Tess",
  "Atlantic City",
  "Chariots of Fire",
  "On Golden Pond",
  "Reds",
  "Gandhi",
  "Missing",
  "The Verdict",
  "The Dresser",
  "The Right Stuff",
  "Tender Mercies",
  "The Killing Fields",
  "A Passage to India",
  "Places in the Heart",
  "A Soldier's Story",
  "Kiss of the Spider Woman",
  "Out of Africa",
  "Prizzi's Honor",
  "Witness",
  "Children of a Lesser God",
  "Hannah and Her Sisters",
  "The Mission",
  "A Room with a View",
  "Hope and Glory",
  "The Last Emperor",
  "The Accidental Tourist",
  "Dangerous Liaisons",
  "Mississippi Burning",
  "My Left Foot",
  "Awakenings",
  "The Godfather Part III",
  "Bugsy",
  "JFK",
  "The Prince of Tides",
  "The Crying Game",
  "Howards End",
  "Scent of a Woman",
  "In the Name of the Father",
  "The Piano",
  "The Remains of the Day",
  "Quiz Show",
  "The Shawshank Redemption",
  "Babe",
  "Il Postino: The Postman",
  "Sense and Sensibility",
  "The English Patient",
  "Secrets & Lies",
  "Shine",
  "The Full Monty",
  "L.A. Confidential",
  "Elizabeth",
  "Life Is Beautiful",
  "The Thin Red Line",
  "American Beauty",
  "The Cider House Rules",
  "The Insider",
  "Chocolat",
  "Crouching Tiger, Hidden Dragon",
  "Erin Brockovich",
  "Traffic",
  "Gosford Park",
  "In the Bedroom",
  "Gangs of New York",
  "The Hours",
  "The Pianist",
  "Master and Commander: The Far Side of the World",
  "Mystic River",
  "Seabiscuit",
  "Finding Neverland",
  "Ray",
  "Sideways",
  "Capote",
  "Crash",
  "Good Night, and Good Luck",
  "Munich",
  "Babel",
  "Letters from Iwo Jima",
  "The Queen",
  "Atonement",
  "Michael Clayton",
  "Frost/Nixon",
  "Milk",
  "The Reader",
  "The Blind Side",
  "District 9",
  "An Education",
  "The Hurt Locker",
  "Inglourious Basterds",
  "Precious",
  "A Serious Man",
  "Up in the Air",
  "Black Swan",
  "The Fighter",
  "The Kids Are All Right",
  "The King's Speech",
  "127 Hours",
  "The Social Network",
  "True Grit",
  "Winter's Bone",
  "The Artist",
  "The Descendants",
  "Extremely Loud & Incredibly Close",
  "The Help",
  "Hugo",
  "Midnight in Paris",
  "Moneyball",
  "The Tree of Life",
  "War Horse",
  "Amour",
  "Argo",
  "Beasts of the Southern Wild",
  "Django Unchained",
  "Les Misérables",
  "Lincoln",
  "Silver Linings Playbook",
  "Zero Dark Thirty",
  "American Hustle",
  "Captain Phillips",
  "Dallas Buyers Club",
  "Her",
  "Nebraska",
  "Philomena",
  "12 Years a Slave",
  "The Wolf of Wall Street",
  "American Sniper",
  "Birdman or (The Unexpected Virtue of Ignorance)",
  "Boyhood",
  "The Grand Budapest Hotel",
  "The Imitation Game",
  "Selma",
  "The Theory of Everything",
  "Whiplash",
  "The Big Short",
  "Bridge of Spies",
  "Brooklyn",
  "Mad Max: Fury Road",
  "Room",
  "Spotlight",
  "Arrival",
  "Fences",
  "Hacksaw Ridge",
  "Hell or High Water",
  "Hidden Figures",
  "La La Land",
  "Lion",
  "Manchester by the Sea",
  "Moonlight",
  "Call Me by Your Name",
  "Darkest Hour",
  "Dunkirk",
  "Lady Bird",
  "Phantom Thread",
  "The Post",
  "The Shape of Water",
  "Three Billboards Outside Ebbing, Missouri",
  "BlacKkKlansman",
  "The Favourite",
  "Green Book",
  "Roma",
  "Vice",
  "Ford v Ferrari",
  "The Irishman",
  "Jojo Rabbit",
  "Little Women",
  "Marriage Story",
  "1917",
  "Once Upon a Time in Hollywood",
  "The Father",
  "Judas and the Black Messiah",
  "Mank",
  "Minari",
  "Nomadland",
  "Promising Young Woman",
  "Sound of Metal",
  "The Trial of the Chicago 7",
  "Belfast",
  "CODA",
  "Don't Look Up",
  "King Richard",
  "Licorice Pizza",
  "Nightmare Alley",
  "The Power of the Dog",
  "West Side Story",
  "American Fiction",
  "Maestro",
  "A Complete Unknown",
  "Conclave",
  "Emilia Pérez",
  "I'm Still Here",
  "Nickel Boys",
  "The Substance",
  "Bugonia",
  "Frankenstein",
  "Hamnet",
  "Marty Supreme",
  "One Battle After Another",
  "Sentimental Value",
  "Sinners",
  "The Secret Agent",
  "Train Dreams",
];
