/** Starter movie titles for bulk import. Edit this list as needed. */
export const STARTER_MOVIES: string[] = [
  "Back to the Future",
  "Jurassic Park",
  "The Matrix",
  "Ghostbusters",
  "Die Hard",
  "Jaws",
  "Alien",
  "The Terminator",
  "Terminator 2: Judgment Day",
  "The Dark Knight",
  "Titanic",
  "Star Wars",
  "The Empire Strikes Back",
  "Return of the Jedi",
  "Raiders of the Lost Ark",
  "Indiana Jones and the Last Crusade",
  "E.T. the Extra-Terrestrial",
  "Jurassic World",
  "Avatar",
  "The Avengers",
  "Avengers: Endgame",
  "Iron Man",
  "Spider-Man",
  "Spider-Man: No Way Home",
  "Batman Begins",
  "The Dark Knight Rises",
  "Superman",
  "Man of Steel",
  "Guardians of the Galaxy",
  "Black Panther",
  "Rocky",
  "Rocky II",
  "Rambo: First Blood",
  "Top Gun",
  "Top Gun: Maverick",
  "The Karate Kid",
  "The Hunger Games",
  "Mad Max: Fury Road",
  "Gladiator",
  "Braveheart",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lord of the Rings: The Two Towers",
  "The Lord of the Rings: The Return of the King",
  "The Hobbit: An Unexpected Journey",
  "Harry Potter and the Sorcerer's Stone",
  "Harry Potter and the Prisoner of Azkaban",
  "Harry Potter and the Deathly Hallows – Part 2",
  "The Shawshank Redemption",
  "Forrest Gump",
  "The Godfather",
  "The Godfather Part II",
  "Goodfellas",
  "Pulp Fiction",
  "Fight Club",
  "Se7en",
  "The Silence of the Lambs",
  "American Beauty",
  "Saving Private Ryan",
  "Schindler's List",
  "The Green Mile",
  "Inception",
  "Interstellar",
  "The Prestige",
  "Dunkirk",
  "2001: A Space Odyssey",
  "A Clockwork Orange",
  "The Shining",
  "Blade Runner",
  "Blade Runner 2049",
  "The Sixth Sense",
  "Signs",
  "Unbreakable",
  "Get Out",
  "A Quiet Place",
  "Scream",
  "Halloween",
  "The Exorcist",
  "Nightmare on Elm Street",
  "Beetlejuice",
  "Edward Scissorhands",
  "Mrs. Doubtfire",
  "Home Alone",
  "Home Alone 2: Lost in New York",
  "Groundhog Day",
  "Ferris Bueller's Day Off",
  "The Breakfast Club",
  "Clueless",
  "Mean Girls",
  "Legally Blonde",
  "Anchorman: The Legend of Ron Burgundy",
  "Step Brothers",
  "Superbad",
  "The Hangover",
  "Toy Story",
  "Toy Story 2",
  "Toy Story 3",
  "The Incredibles",
  "Finding Nemo",
  "Shrek",
  "Shrek 2",
  "Frozen",
];
